### ISSUE TITLE
Limit payment methods selection to acceptor's available methods

### ISSUE THREAD

**Issue by benbehringer** [taptreepay/taptree-woocommerce#7]
**Enhancement**
Make a call to the API's acceptor endpoint to retrieve unlocked/available payment methods.

Users then might turn them off in the plugin. Yet it is still under discussion if changing the settings here should also disable the method in the acceptor.

![](https://user-images.githubusercontent.com/37022575/210555710-917fb472-9486-4eec-b783-f78a0389ef36.png)

**Comment by aaronensslin** [comment]
bc904304c7d651ae046e1c85c137333df4b263f8
